### ISSUE TITLE
Browserify - can't find module

### ISSUE THREAD

**Issue by rogchap** [brianium/watermarkjs#15]
I'm having an issue where when adding watermarkjs via Browserify that it can't find the `./lib/images`, `./lib/functions` etc  modules in `node_modules/watermarkjs/dist`.

I'm just using `watermark = require('watermarkjs')` 

Any thoughts?

**Comment by brianium** [comment]
A bit of an oversight on my part, but watermark was not built as a UMD module. The index.js file defines an export and then sets the `watermark` function on `window` directly. 

This should be a pretty easy fix, as Browserify has an option for it. I'll do a new build and tag a release later today. In the meantime you should be able to import the script directly and access watermark in the global space:

```js
require('watermarkjs'); //no return value

window.watermark(...);
```

Or include the script directly in a page.

**Comment by brianium** [comment]
@rogchap I just pushed a 1.1.0 release that should address the module issue. Can you confirm it works for you?

Thanks!

**Comment by rogchap** [comment]
Thanks @brianium that did the job. Thanks for a quick fix. :)
