### ISSUE TITLE
for each

### ISSUE THREAD

**Issue by ixlipixli** [brianium/watermarkjs#18]
Hi,
I am having trouble to use your plugin on several images where I loop through with a $('element').each(function...

If I try to append the img to $(this) it doesnt work, but if I write the class hardcoded it works.
For me it looks like the this part `.then(function(img){
						$(this).append(img);
					});` doesn't work because "this" is not defined anymore...

Am I doing something wrong here?

**Comment by brianium** [comment]
Ah. Yeah. I think the `this` context has changed within the promise function. You might try something like this:

```
.then(function(img) {
  $(this).append(img);
}.bind(this));
```

That should preserve the context created by jQuery. Let me know if that helps :)
