### ISSUE TITLE
Multiple Image Issue

### ISSUE THREAD

**Issue by JeffWeb9999** [brianium/watermarkjs#19]
I have multiple product images in a "c:forEach" statement on the site and each product has its own row and product image div but the code appears to be taking the image out of the product image div and merging all the images in one div causing all the images to flow right below each other and not in their respective div's. Just wondering if you have ever seen this or if i may be forgetting something. Thank You!
![capture](https://cloud.githubusercontent.com/assets/17913916/13860914/0f3b6480-ec61-11e5-84eb-28c4e52e2132.PNG)

**Comment by brianium** [comment]
@JeffWeb9999 I don't think I have enough information. Can you paste a code snippet of how you are using watermarkjs?

**Comment by JeffWeb9999** [comment]
Sure, here is the sample, inside the c:forEach item I have a productImage div that contains the watermark JS code. I've included the link to watermark.js in the head of my page.
<c:forEach var="item" items="..." begin="0" end="...">
...
<div id="productImage">
<script>
watermark(['/shop/images/productImage.jpg', '/shop/images/logo/eng/png/watermark.png'])														.image(watermark.image.center(0.5))
then(function (img) {												     document.getElementById('productImage').appendChild(img);
});
</script>
</div>
</c:forEach>
Thanks!

**Comment by brianium** [comment]
Hmmmm... It seems like you are spitting multiple divs out with the same id - that is `productImage`. ID's should be unique, so I bet the append is just picking the first div with that ID

**Comment by JeffWeb9999** [comment]
Ok, thanks. That makes sense and worked. Thank you!

**Comment by brianium** [comment]
Awesome! No problem.
