### ISSUE TITLE
get original image

### ISSUE THREAD

**Issue by shahroq** [brianium/watermarkjs#20]
Hi,
As long as watermark printed by js, is it possible for a user to get original images by Inspector or any other tool?

**Comment by brianium** [comment]
@shahroq if you are applying watermarks to images that are already on the page, then yes there will be a way to view the original image.

However - you can use watermarkjs to watermark `File` objects during an upload process, and this process will shield the original image from being viewed. Uploads are really the only safe bet when it comes to watermarking in the browser.
