### ISSUE TITLE
Upload image in portrait format

### ISSUE THREAD

**Issue by jeremie-huy** [brianium/watermarkjs#21]
Hello,

I'm having an issue with the upload part.
When I'm trying to upload an image in portrait format, I get it back in landscape format.

It seems to be the case too in the upload demo (http://brianium.github.io/watermarkjs/uploading.html)

Any idea?

Thanks

**Comment by brianium** [comment]
@jeremie-huy hi!

I have not experienced this particular issue before. I just tried it with another portrait style image and it worked fine.

What browser and operating system are you using?

 Are you able to share the image you are using?

Thanks!

**Comment by jeremie-huy** [comment]
Hi,

I just tried it on my office computer (ubuntu/chrome) and it works fine.

I had the issue on my macbook (os x 10.11/chrome) with any image with a height larger than its width.

Thanks

**Comment by brianium** [comment]
What version of Chrome on OS X? I am on OS X 10.10 and the latest version of Chrome and unable to reproduce.

**Comment by brianium** [comment]
I will try testing on 10.11 as well

**Comment by jeremie-huy** [comment]
Chrome version is 49.0.2623.108 (64-bit)

**Comment by brianium** [comment]
@jeremie-huy I can't seem to reproduce this issue ¯\\\_(ツ)_/¯

I'm not entirely sure what could be causing it either. I'll leave this open for a while longer in case someone else encounters it.

Thank you for opening the issue :)

**Comment by jeremie-huy** [comment]
Sorry for wasting your time :(
If I find something, I'll keep you informed.

**Comment by brianium** [comment]
Sorry for the late response. Not a waste of time at all. Thank you for trying to make this library better :) - I'll keep my eyes peeled too!
