### ISSUE TITLE
How to rotate the watermark text?

### ISSUE THREAD

**Issue by DatzMe101** [brianium/watermarkjs#22]
Its not an issue actually but just want to know if i can rotate the text like slanting or about like this ' / '. Hoping for your response. Thank you for the help.

**Comment by DatzMe101** [comment]
In addition to the concern of mine, how can I set the font size relative to the size of the image. Coz for now I manually set the font size. Is there any way that the size of font become relative to the width of the picture?

**Comment by brianium** [comment]
Take a look at http://brianium.github.io/watermarkjs/text.html - this has an example of rotating text under the "Rotate" heading. That particular function is pretty naive and works for that picture, but it shouldn't be too hard to cook up a function that works across all pictures.

As for relative font-size, that would be something that needs to be implemented. Every watermarking function receives the the target canvas as an argument. This canvas has dimension properties that you could use to figure out an ideal font size :)

Take a look at the [built-in styles](https://github.com/brianium/watermarkjs/tree/master/lib/style) if you want an idea how to get started writing some of these functions. If you come up with something useful, I would be happy to accept a pull request.

**Comment by DatzMe101** [comment]
That was a great response Sir. Im thankful that you respond. Anyway thank you for the rotation matter. And for the font size i just made an alternative by getting the actual width of the picture and divide it to how many characters of my text and thanks it work. Ill let you know if i have some question and thank you for this plugin that save my day :)

**Comment by brianium** [comment]
I'm glad it was useful to you :)
