### ISSUE TITLE
how to wrap text

### ISSUE THREAD

**Issue by nyambayar0613** [brianium/watermarkjs#24]
i want to make text watermark with long. how to wrap text ?

**Comment by brianium** [comment]
Text wrapping has to be done manually with canvases.

This [tutorial](http://www.html5canvastutorials.com/tutorials/html5-canvas-wrap-text-tutorial/) covers an approach.

For an example of writing a custom watermark function, look [here](http://brianium.github.io/watermarkjs/text.html) under the "Rotate" heading.

This would be a handy addition to the core library. Pull requests are always welcome :)
