### ISSUE TITLE
Support  Cordova ?

### ISSUE THREAD

**Issue by xzx689** [brianium/watermarkjs#25]
In app android system was used? In my test app which can not be used. Requesting for help. Thank you

**Comment by yurik94** [comment]
Any news about cordova/ionic support? Thanks!

**Comment by brianium** [comment]
I am not terribly familiar with cordova/ionic. If someone wants to take point - even to definitively answer - then I'm sure that would help clear things up for some folks :)

**Comment by yurik94** [comment]
I think I did it, finally I got it working nicely on **Ionic 2**, if anyone is interested then let me know!

**Comment by brianium** [comment]
👏 👏 👏  - good to hear @yurik94  - I'll close this issue for now and hopefully people find it if they encounter similar problems. I believe you can keep a thread going once it's closed.

**Comment by Alplob** [comment]
Hello @yurik94 ,

Please share how you got this plugin working with Ionic 2/3. I got the following error:
````
Cannot find name 'watermark'.

watermarkjs([targetPath, './assets/logo.png'])
.image(watermark.image.lowerRight(0.5))
.then(function (img) {

});
````

I installed watermarkjs with npm. Also I get the same error withe 'text' when I try to watermark with text.

Thanks!

**Comment by yurik94** [comment]
```
import watermarkjs from "watermarkjs";

@Injectable()
export class XProvider {

public watermark: any;

  constructor(private file: File, private imageResizer: ImageResizer) {
    this.watermark = watermarkjs;
  }

[...]
this.watermark([imageUri, tempLogoPath])
              .blob(this.watermark.image[template.logoPosition.watermarjsFn](template.logoOpacity / 100))
              .then((img: Blob) => {
                this.file.writeFile(this.file.externalApplicationStorageDirectory, new Date().getTime() + '.jpg', img, {replace: true})
                  .then(() => {
                    // remove any remaining canvas references
                    this.watermark.destroy();
                    resolve(img)
                  }, (err) => {
                    reject(err);
                    this.watermark.destroy();
                  });
              });
[...]
```
package.json:

`"watermarkjs": "^2.0.0",`

**Comment by yurik94** [comment]
Anyway I think that a native watermark should be more memory safe and a lot faster!
