### ISSUE TITLE
When use other web's image get error

### ISSUE THREAD

**Issue by altaihero** [brianium/watermarkjs#26]
Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

I am using with facebook profile picture but i got error

**Comment by altaihero** [comment]
I handled for me with image to base64

function toDataUrl(url, callback, outputFormat){
          var img = new Image();
          img.crossOrigin = 'Anonymous';
          img.onload = function(){
              var canvas = document.createElement('CANVAS');
              var ctx = canvas.getContext('2d');
              var dataURL;
              canvas.height = this.height;
              canvas.width = this.width;
              ctx.drawImage(this, 0, 0);
              dataURL = canvas.toDataURL(outputFormat);
              callback(dataURL);
              canvas = null;
          };
          img.src = url;
      }

      toDataUrl('http://fbcdn-profile-a.akamaihd.net/hprofile-ak-xaf1/v/t1.0-1/s200x200/12987212_1105091976214974_7536770153945061614_n.jpg?oh=e39b38e77dfefe0b02c461d41e33ac64&oe=57AA36FD&__gda__=1474458678_9fbd75d9519fae1601b574c59b62cf79', function(base64Img){
          watermark(['http://watermark.dev/img/shepherd.jpg', base64Img])
                  .image(watermark.image.lowerRight(1))
                  .then(function (img) {
                      var pre = document.querySelector('#lower-right pre');
                      pre.parentNode.insertBefore(img, pre);
                  });
      });

**Comment by brianium** [comment]
@altaihero glad you figured something out that works.

Usually with tainted canvas data, it has to do with cross domain images being loaded. `watermarkjs` provides an `options` object that lets you configure how the image is loaded.

The [documentation](http://brianium.github.io/watermarkjs/docs.html#watermark) for the watermark factory has an example

**Comment by altaihero** [comment]
:+1:  oh nice. sorry about this
