### ISSUE TITLE
Each loop

### ISSUE THREAD

**Issue by xzdshr** [brianium/watermarkjs#30]
Hi!
I have same issue with foreach loop. I'm trying to replace several images but it doesn't work.
       `var images = document.getElementsByClassName('watermark');`
	`for(var i=0; i<images.length; i++){`
		`watermark([images[i].src, logo])`
	          `.image(watermark.image.lowerRight(1))`
	          `.then(function(img){`
	        	`images[i].src = img.src; // Undefined images[i] here`
	          `});`
	`}`

**Comment by vmdao** [comment]
Yes, watermark is Asynchronous. if you use for() not works right.
Try .forEach()

**Comment by xzdshr** [comment]
Works perfectly! Thank you!
