### ISSUE TITLE
cross origin not working

### ISSUE THREAD

**Issue by hdriqi** [brianium/watermarkjs#32]
I already use the init function for cross origin, but still have error like this:
`Image from origin 'https://xxx' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

**Comment by CKAtGitHub** [comment]
i also block by this problem,how you solve it ?

**Comment by edgesoft** [comment]
Same here

**Comment by vmdao** [comment]
In the link ông, you add attribute crossOrigin. Try

**Comment by edgesoft** [comment]
I tried with this but I guess it's a server side thing. If cross origin isn't enabled then the client can't do anything. So I guess this issue should be closed.
