### ISSUE TITLE
Data URI

### ISSUE THREAD

**Issue by ACK19** [brianium/watermarkjs#33]
How would I watermark an image I can only parse as a base 64 string?

**Comment by brianium** [comment]
Does this not work? A data URI should be handled like any other URI. So if `http://mydomain.com/imgs/cat.jpeg` works, I would expect `data:.....` to work as well. Are you seeing an error?

**Comment by brianium** [comment]
All string sources go through the [loadUrl](https://github.com/brianium/watermarkjs/blob/master/lib/image/index.js#L62) function. This should handle a data URI just fine. Let me know if that is not the case :)

**Comment by ACK19** [comment]
Didn't figure that out, it's good
